### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by 3cl1ps** [qbert911/lnd-watcher#3]
Hey, i got 1 error starting the script :
![image](https://user-images.githubusercontent.com/2938587/55313206-7e5e8880-5467-11e9-9f4a-978b0a82c8e4.png)

and a formating issue  : 
![image](https://user-images.githubusercontent.com/2938587/55313231-92a28580-5467-11e9-91d2-759b4e052572.png)

Tell me if you need more infos to debug.

**Comment by qbert911** [comment]
Please try updated version which removes non-printable characters from aliases and let me know what happens.

**Comment by 3cl1ps** [comment]
![image](https://user-images.githubusercontent.com/2938587/55332710-36a32580-5496-11e9-91fd-b2235870ddd3.png)

![image](https://user-images.githubusercontent.com/2938587/55333045-c77a0100-5496-11e9-8a02-6129d9e132ff.png)


There is still the weird line between init = false & init = true (see first comment). I don't know if that's normal.
edit : i think that node 's name is causing issue : https://1ml.com/node/032c9bab7bf5c3b17ad231c617315890861227a802b422c62422cf03bf4f089a0c

**Comment by qbert911** [comment]
Well spotted 👍 
I pushed new version removing & symbol from display. 
Thank You!

**Comment by 3cl1ps** [comment]
still got the erro line 105

**Comment by qbert911** [comment]
Looks like its choking on a color code or something. Please send me a file "lncli listchannels > debug.txt"

**Comment by 3cl1ps** [comment]
paste : 
https://termbin.com/abnl

**Comment by qbert911** [comment]
Chased my tail for a long time until I figured out the error (I hope) ... your node had more capacity then I planned for so I added another digit and things got better on my end. 

Please let me know if it works for you 🐙

**Comment by 3cl1ps** [comment]
all good ! thanks

**Comment by babikpatient6** [comment]
> There is still the weird line between init = false & init = true (see first comment). I don't know if that's normal. edit : i think that node 's name is causing issue : https://1ml.com/node/032c9bab7bf5c3b17ad231c617315890861227a802b422c62422cf03bf4f089a0c

Are you the owner of this node if I understand it right?
https://mempool.space/lightning/node/032c9bab7bf5c3b17ad231c617315890861227a802b422c62422cf03bf4f089a0c

I am helping someone to recover funds and one of his zombie channels is with your old node. If you still have seed or original node's wallet.db (xprv can be extracted from it). We can "close" that channel with chantools. 
Pls send me email to bambim1959@gmail.com ASAP.

**Comment by 3cl1ps** [comment]
Hi, I’m not.

**Comment by babikpatient6** [comment]
Ahh, I've misunderstood then, sry..
